export { default as AmiriBold } from './Amiri-Bold.ttf'
export { default as AmiriBoldItalic } from './Amiri-BoldItalic.ttf'
export { default as AmiriItalic } from './Amiri-Italic.ttf'
export { default as AmiriRegular } from './Amiri-Regular.ttf'
export { default as Northwell } from './Northwell.ttf'
